/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ACausa;

import ACausa.view.MenuView;

public class App {

    public static void main(String[] args) {
        MenuView menu = new MenuView();
        menu.start();
    }
}
